# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='latitude',
            field=models.FloatField(default=32.7833333),
        ),
        migrations.AddField(
            model_name='photo',
            name='longitude',
            field=models.FloatField(default=-96.797),
        ),
    ]
