# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20160527_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.FileField(upload_to='photos/upload/photos'),
        ),
    ]
