# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20160527_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='location_string',
            field=models.CharField(default='The World', max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='purchase_link',
            field=models.CharField(default='http://www.lightontime.co', max_length=200),
        ),
    ]
