# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20160527_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.FileField(upload_to='photos/static/photos/upload'),
        ),
    ]
