# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20160530_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_file',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='width_field',
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(default='http://www.codyscapes.com/gallery/', max_length=200),
        ),
    ]
