# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_photo_isphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
