# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-10 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_photo_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='purchase_link',
            field=models.CharField(default='http://www.codyscapes.com', max_length=200),
        ),
    ]
