# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-10 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20170810_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
