# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-06 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_photo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='recent',
            field=models.BooleanField(default=False),
        ),
    ]
